# vim: ts=2 sw=2 et ft=ansible.yaml
---
# tasks file for nrg.godaddy
- name: setup api_server_url
  set_fact:
    api_server_url: '{{api_server}}/v{{api_version}}/domains/{{domain_name}}/records/{{type}}/{{record_name}}'
    authorization:  'sso-key {{api_key}}:{{api_secret}}'
    need_delete:    False

- name: call godaddy api to update/create new record
  uri:
    url:          '{{api_server_url}}'
    method:       DELETE
    body_format:  json
    headers:
      Authorization: '{{authorization}}'
